#!/usr/bin/env sh
# Dont warn on the word `local`
# shellcheck disable=SC3043

# Playwright-based TMDB login script.
# Solves AWS WAF JS challenge and exports session cookies to Netscape format.
# Run once on machine with display (or Xvfb).
#
# Version 0.1.0 (Released 2026-07-27)
#   * Initial implementation

. "$(dirname "$0")/connect/scripts_common.sh"
load_config "$(dirname "$0")/connect"

: "${TMDB_USERNAME:=}"
: "${TMDB_PASSWORD:=}"
: "${TMDB_COOKIE_FILE:=${HOME}/.tmdb_cookies.txt}"
: "${DEBUG:=false}"

_COOKIE_FILE="${TMDB_COOKIE_FILE}"

while [ $# -gt 0 ]; do
    case "$1" in
        --cookies)
            case "$2" in
                '') echo "ERROR: --cookies requires a file path" >&2; exit 1 ;;
                *) _COOKIE_FILE="$2"; shift 2 ;;
            esac
            ;;
        --debug) DEBUG=true; shift ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Playwright-based TMDB login. Exports session cookies to Netscape format."
            echo "Run once on machine with display (or Xvfb)."
            echo ""
            echo "Options:"
            echo "  --cookies <file>  Output cookie file (default: ~/.tmdb_cookies.txt)"
            echo "  --debug           Verbose logging"
            echo "  -h, --help        Show this help"
            exit 0
            ;;
        *) echo "ERROR: Unknown flag: $1" >&2; exit 1 ;;
    esac
done

if [ -z "${TMDB_USERNAME}" ] || [ -z "${TMDB_PASSWORD}" ]; then
    echo "ERROR: TMDB_USERNAME and TMDB_PASSWORD must be set in scripts.conf" >&2
    exit 1
fi

if ! command -v node >/dev/null 2>&1; then
    echo "ERROR: node not found. Install Node.js." >&2
    exit 127
fi

if ! node -e "require('playwright')" 2>/dev/null; then
    echo "ERROR: playwright not found. Run: npm install playwright && npx playwright install chromium" >&2
    exit 127
fi

debug_log "Launching Playwright for TMDB login..."

_PLAYWRIGHT_SCRIPT=$(cat << 'NODESCRIPT'
const { chromium } = require('playwright');
const fs = require('fs');

(async () => {
    const username = process.env.TMDB_USERNAME;
    const password = process.env.TMDB_PASSWORD;
    const cookieFile = process.env.TMDB_COOKIE_FILE;

    if (!username || !password) {
        console.error('ERROR: TMDB_USERNAME and TMDB_PASSWORD must be set');
        process.exit(1);
    }

    const browser = await chromium.launch({
        headless: false,
        args: ['--disable-blink-features=AutomationControlled']
    });
    const context = await browser.newContext({
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
        viewport: { width: 1280, height: 720 },
        locale: 'en-US',
    });
    await context.addInitScript(() => {
        Object.defineProperty(navigator, 'webdriver', { get: () => false });
    });
    const page = await context.newPage();

    try {
        console.error('Navigating to TMDB login...');
        await page.goto('https://www.themoviedb.org/login', { waitUntil: 'networkidle' });

        console.error('Filling credentials...');
        await page.fill('#username', username);
        await page.fill('#password', password);

        console.error('Submitting login...');
        await Promise.all([
            page.waitForNavigation({ timeout: 30000 }),
            page.click('#login_button'),
        ]);

        const loggedIn = await page.locator('header ul > li.user').count();
        if (loggedIn === 0) {
            console.error('ERROR: Login failed. Check credentials.');
            process.exit(1);
        }

        console.error('Login successful. Exporting cookies...');

        const cookies = await context.cookies();
        const lines = ['# Netscape HTTP Cookie File', '# Generated by tmdb_login.sh', ''];

        for (const c of cookies) {
            const domain = c.domain.startsWith('.') ? c.domain : '.' + c.domain;
            const flag = 'TRUE';
            const path = c.path || '/';
            const secure = c.secure ? 'TRUE' : 'FALSE';
            const expiry = c.expires > 0 ? Math.floor(c.expires) : 0;
            lines.push([domain, flag, path, secure, expiry, c.name, c.value].join('\t'));
        }

        fs.writeFileSync(cookieFile, lines.join('\n') + '\n');
        console.log(cookieFile);
        console.error('Cookies exported to ' + cookieFile);

    } catch (err) {
        console.error('ERROR:', err.message);
        process.exit(1);
    } finally {
        await browser.close();
    }
})();
NODESCRIPT
)

TMDB_USERNAME="${TMDB_USERNAME}" TMDB_PASSWORD="${TMDB_PASSWORD}" TMDB_COOKIE_FILE="${_COOKIE_FILE}" \
    node -e "${_PLAYWRIGHT_SCRIPT}"

debug_log "tmdb_login.sh completed"
